# Site settings
title: Ryan Painter Design
email: rpainterj@gmail.com
description: My work and design.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: rpainterj
github_username:  rpainterj

# Build settings
markdown: kramdown
